import javax.swing.*;
import java.awt.*;

public class Calculator {
    JPanel windowContent;
    JTextField displayField;
    JButton button0;
    JButton button1;
    JButton button2;
    JButton button3;
    JButton button4;
    JButton button5;
    JButton button6;
    JButton button7;
    JButton button8;
    JButton button9;
    JButton buttonPoint;
    JButton buttonEqual;
    JButton buttonPlus;
    JButton buttonMinus;
    JButton buttonStr;
    JButton buttonDiv;
    JButton buttonC;
    JPanel p1;
    JPanel p2;
    Calculator(){
        windowContent= new JPanel();
        BorderLayout bl = new BorderLayout();
    windowContent.setLayout(bl);
    displayField = new JFormattedTextField();
    displayField.setHorizontalAlignment(JFormattedTextField.RIGHT);
    windowContent.add("North",displayField);
    button0=new JButton("0");
    button1=new JButton("1");
    button2=new JButton("2");
    button3=new JButton("3");
    button4=new JButton("4");
    button5=new JButton("5");
    button6=new JButton("6");
    button7=new JButton("7");
    button8=new JButton("8");
    button9=new JButton("9");
    buttonPoint = new JButton(".");
        buttonC = new JButton("C");
    buttonEqual=new JButton("=");
        buttonPlus=new JButton("+");
        buttonMinus=new JButton("-");
        buttonStr=new JButton("*");
        buttonDiv=new JButton("/");
    p1 = new JPanel();
    GridLayout gl =new GridLayout(4,3);
    p1.setLayout(gl);
    p1.add(button1);
    p1.add(button2);
    p1.add(button3);
    p1.add(button4);
    p1.add(button5);
    p1.add(button6);
    p1.add(button7);
    p1.add(button8);
    p1.add(button9);
    p1.add(button0);
    p1.add(buttonPoint);
    p1.add(buttonEqual);
        p2 = new JPanel();
        GridLayout b2 = new GridLayout(4, 1);
        p2.setLayout(b2);
        p2.add(buttonPlus);
        p2.add(buttonMinus);
        p2.add(buttonStr);
        p2.add(buttonDiv);
        windowContent.add("East", p2);
    windowContent.add("Center",p1);
    JFrame frame = new JFrame("Calculator");
    frame.setContentPane(windowContent);
    frame.pack();
    frame.setVisible(true);

    CalculatorEngine ce = new CalculatorEngine(this);
    button0.addActionListener(ce);
    button1.addActionListener(ce);
        button2.addActionListener(ce);
        button3.addActionListener(ce);
        button4.addActionListener(ce);
        button5.addActionListener(ce);
        button6.addActionListener(ce);
        button7.addActionListener(ce);
        button8.addActionListener(ce);
        button9.addActionListener(ce);
    buttonEqual.addActionListener(ce);
        buttonEqual.addActionListener(ce);
        buttonPoint.addActionListener(ce);
        buttonPlus.addActionListener(ce);
        buttonMinus.addActionListener(ce);
        buttonDiv.addActionListener(ce);
        buttonStr.addActionListener(ce);
}
public static void main(String[] args) {
        Calculator calc = new Calculator();
}
}
